# Generated by Django 4.0.2 on 2022-02-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_athlete_options_alter_athlete_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='weight'),
        ),
    ]
