# Generated by Django 4.0.2 on 2022-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_athlete_height_alter_athlete_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Ectomorphs', 'Ectomorphs'), ('Mesomorphs', 'Mesomorphs'), ('Endomorphs', 'Endomorphs'), ('Ecto-mesomorphs', 'Ecto-mesomorphs'), ('Meso-endomorphs', 'Meso-endomorphs'), ('Ecto-Endomorphs', 'Ecto-Endomorphs')], max_length=50, null=True, verbose_name='Body Type'),
        ),
    ]
