# Generated by Django 4.0.2 on 2022-03-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_athlete_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='user_image',
            field=models.ImageField(blank=True, default='static/nothing.jpg', null=True, upload_to=None, verbose_name='Profile Image'),
        ),
    ]
