# Generated by Django 4.0.2 on 2022-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_athlete_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={},
        ),
        migrations.AlterModelManagers(
            name='athlete',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='password',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='user_image',
            field=models.ImageField(blank=True, default='static/DU.jpg', null=True, upload_to=None, verbose_name='Profile Image'),
        ),
    ]
