# Generated by Django 4.0.2 on 2022-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_athlete_options_alter_athlete_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='user_image',
            field=models.ImageField(blank=True, default='DU.jpg', null=True, upload_to=None, verbose_name='Profile Image'),
        ),
    ]
