# Generated by Django 4.0.2 on 2022-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_athlete_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='user_image',
            field=models.ImageField(default='DU.jpg', upload_to=None, verbose_name='Profile Image'),
        ),
    ]
