# Generated by Django 4.0.2 on 2022-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_alter_exercise_exercise_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_image',
            field=models.ImageField(blank=True, null=True, upload_to='Exercise/', verbose_name='Exercise Image'),
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Exercise/Category/', verbose_name='Category Image'),
        ),
    ]
