# Generated by Django 4.0.2 on 2022-02-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0003_alter_exercise_exercise_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exercise.exercisecategory', verbose_name='Exercise Category'),
        ),
    ]
