# Generated by Django 4.0.2 on 2022-02-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0005_domain_remove_exerciseplanitems_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplanitems',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exercise.domain', verbose_name='Domain'),
        ),
    ]
