# Generated by Django 4.0.2 on 2022-02-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0006_exerciseplanitems_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplanitems',
            name='exercise_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exercise.exercisecategory', verbose_name='Exercise Category'),
        ),
    ]
