# Generated by Django 4.0.2 on 2022-03-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_athlete_options_alter_athlete_managers_and_more'),
        ('Exercise', '0009_alter_exerciseplanitems_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_image',
            field=models.ImageField(blank=True, default='static/DE.png', null=True, upload_to='Exercise/', verbose_name='Exercise Image'),
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='image',
            field=models.ImageField(blank=True, default='static/DE.png', null=True, upload_to='Exercise/Category/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='exerciseplan',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.athlete', verbose_name='Athlete'),
        ),
    ]
