# Generated by Django 4.0.2 on 2022-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0010_alter_exercise_exercise_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_image',
            field=models.ImageField(blank=True, default='DE.png', null=True, upload_to='Exercise/', verbose_name='Exercise Image'),
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='image',
            field=models.ImageField(default='DE.png', upload_to='Exercise/Category/', verbose_name='Category Image'),
        ),
    ]
