# Generated by Django 4.0.2 on 2022-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0013_alter_exerciseplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplanitems',
            name='days',
            field=models.CharField(blank=True, choices=[('شنبه', 'Saturday'), ('یکشنبه', 'Sunday'), ('دوشنبه', 'Monday'), ('سه شنبه', 'Tuesday'), ('چهارشنبه', 'Wednesday'), ('پنج شنبه', 'Thursday'), ('جمعه', 'Friday')], max_length=15, null=True),
        ),
    ]
