# Generated by Django 4.0.2 on 2022-05-23 23:07

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0015_alter_exerciseplan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplan',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='exerciseplan',
            name='start_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
