# Generated by Django 4.0.2 on 2022-02-10 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50, verbose_name='Medicine Name')),
                ('medicine_image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Medicine Image')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('CUT', 'cut'), ('UP', 'up'), ('DIET', 'diet')], max_length=50, verbose_name='Status')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('medicine_details', models.TextField(verbose_name='Medicine Details')),
                ('days', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=15)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicineplan_items', to='Medicine.medicine', verbose_name='Medicine')),
                ('medicine_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicineplan_items', to='Medicine.medicineplan', verbose_name='Medicine Plan')),
            ],
        ),
        migrations.AddField(
            model_name='medicineplan',
            name='foods',
            field=models.ManyToManyField(through='Medicine.MedicinePlanItems', to='Medicine.Medicine', verbose_name='Medicine'),
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Category Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medicine.medicinecategory', verbose_name='Parent')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicinecategory', verbose_name='Medicine Category'),
        ),
    ]
