# Generated by Django 4.0.2 on 2022-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='Medicine/', verbose_name='Medicine Image'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Medicine/Category/', verbose_name='Category Image'),
        ),
    ]
