# Generated by Django 4.0.2 on 2022-03-06 02:04

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_alter_medicine_medicine_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineplan',
            name='foods',
        ),
        migrations.AddField(
            model_name='medicineplan',
            name='medicine',
            field=models.ManyToManyField(through='Medicine.MedicinePlanItems', to='Medicine.Medicine', verbose_name='Medicine'),
        ),
        migrations.AddField(
            model_name='medicineplanitems',
            name='medicine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicinecategory', verbose_name='Food Category'),
        ),
        migrations.AlterField(
            model_name='medicineplanitems',
            name='medicine',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='medicine_category', chained_model_field='medicine_category', on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicine', verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='medicineplanitems',
            name='medicine_details',
            field=models.CharField(max_length=100, verbose_name='Medicine Details'),
        ),
    ]
