# Generated by Django 4.0.2 on 2022-03-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_athlete_options_alter_athlete_managers_and_more'),
        ('Medicine', '0003_remove_medicineplan_foods_medicineplan_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, default='static/DM.jpg', null=True, upload_to='Medicine/', verbose_name='Medicine Image'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='image',
            field=models.ImageField(blank=True, default='static/DM.jpg', null=True, upload_to='Medicine/Category/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='medicineplan',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.athlete', verbose_name='Athlete'),
        ),
    ]
