# Generated by Django 4.0.2 on 2022-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0005_alter_medicine_medicine_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(default='DM.jpg', upload_to='Medicine/', verbose_name='Medicine Image'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='image',
            field=models.ImageField(default='DM.jpg', upload_to='Medicine/Category/', verbose_name='Category Image'),
        ),
    ]
