# Generated by Django 4.0.2 on 2022-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0006_alter_medicine_medicine_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineplan',
            name='status',
            field=models.CharField(choices=[('کات', 'cut'), ('افزایش وزن', 'up'), ('کاهش وزن', 'diet')], max_length=50, verbose_name='Status'),
        ),
    ]
