# Generated by Django 4.0.2 on 2022-02-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('CUT', 'cut'), ('UP', 'up'), ('DIET', 'diet')], max_length=50, verbose_name='Status')),
                ('system_number', models.CharField(max_length=50, verbose_name='System Number')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, verbose_name='Food Name')),
                ('food_image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Food Image')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('food_details', models.TextField(verbose_name='Food Details')),
                ('days', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=15)),
                ('food_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodplan_items', to='Food.foodplan', verbose_name='Food Plan')),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodplan_items', to='Food.foods', verbose_name='Food')),
            ],
        ),
        migrations.AddField(
            model_name='foodplan',
            name='foods',
            field=models.ManyToManyField(through='Food.FoodPlanItems', to='Food.Foods', verbose_name='Foods'),
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Category Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.foodcategory', verbose_name='Parent')),
            ],
        ),
    ]
