# Generated by Django 4.0.2 on 2022-02-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Food.foodcategory', verbose_name='Food Category'),
            preserve_default=False,
        ),
    ]
