# Generated by Django 4.0.2 on 2022-02-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Food', '0002_foods_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplan',
            name='system_number',
        ),
        migrations.AddField(
            model_name='foodplan',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.athlete', verbose_name='Athlete'),
        ),
    ]
