# Generated by Django 4.0.2 on 2022-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_remove_foodplan_system_number_foodplan_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Food/Category/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='Food/', verbose_name='Food Image'),
        ),
    ]
