# Generated by Django 4.0.2 on 2022-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_foodplanitems_food_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplanitems',
            name='food_details',
            field=models.CharField(max_length=100, verbose_name='Food Details'),
        ),
    ]
