# Generated by Django 4.0.2 on 2022-03-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_alter_foodplanitems_food_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.foodcategory', verbose_name='Parent'),
        ),
    ]
