# Generated by Django 4.0.2 on 2022-03-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_alter_foodcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.foodcategory', verbose_name='Parent'),
        ),
    ]
