# Generated by Django 4.0.2 on 2022-05-06 05:42

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0011_alter_foodcategory_image_alter_foods_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplanitems',
            name='foods',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='food_category', chained_model_field='food_category', on_delete=django.db.models.deletion.CASCADE, to='Food.foods', verbose_name='Food'),
        ),
    ]
