# Generated by Django 4.0.2 on 2022-06-05 09:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0015_alter_foodplan_status_alter_foodplanitems_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplan',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='foodplan',
            name='start_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
